apiVersion: apps/v1
kind: Deployment
metadata:
  name: neck-head-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neck-head
  template:
    metadata:
      labels:
        app: neck-head
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: hcp-master
      containers:
      - name: neck-head
        image: ketidevit2/neck-head-slim:1.0.3
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: neck-head-service
spec:
  type: NodePort
  selector:
    app: neck-head
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080